### ISSUE TITLE
Live editor ruined my game completely

### ISSUE THREAD

**Issue by Zubo03** [xAranaktu/FIFA-23-Live-Editor#106]
I downloaded the LE and when it gave me the can't find game after 1200 attempts I deleted it. But when I tried to start the game normally, it still tried to start with the fake Anti Cheat and failed to start the game. I deleted the Anti Cheat, deleted the anti cheat files from the game directories and reinstalled EA's anticheat but it still won't run.

**Comment by xAranaktu** [comment]
If you have closed the launcher before it managed to restore original EA Anticheat then now you need to repair the game on EA App. If repairing also won't work then you need to do full game reinstall.
