### ISSUE TITLE
Directories...

### ISSUE THREAD

**Issue by Kobi-Blade** [xAranaktu/FIFA-23-Live-Editor#109]
Lets us customise which directories the Live Editor use, I don't want any files on

> C:\FIFA 23 Live Editor

I'll just use **v23.1.2.3** for now.

**Comment by xAranaktu** [comment]
Added "LE Data Root" to the settings in v23.1.2.5
![image](https://user-images.githubusercontent.com/12433069/233149528-b9e0a38a-b883-474b-8a54-c0e47aeb0804.png)
