### ISSUE TITLE
Team name is error

### ISSUE THREAD

**Issue by jsisam2299887** [xAranaktu/FIFA-23-Live-Editor#113]
![team name](https://user-images.githubusercontent.com/130343998/230843848-1f7cbbe8-4935-49e8-b298-dd701ac60715.png)
The team name show ????. How to fix this problem

**Comment by xAranaktu** [comment]
Your language isn't supported. 
Start new career with [English squad file](https://mega.nz/folder/wZN3mDQR#_LvMxv1dEC1TgwOadPkBuQ).
