### ISSUE TITLE
fifa wont open

### ISSUE THREAD

**Issue by chrisakmen** [xAranaktu/FIFA-23-Live-Editor#12]
Hello!

My problem is that whenever I 'Run Game' in LE fifa starts to open, steam laucher opens but the game doesnt. Only thing that opens after the steam is origin (no error no nothing)

**Comment by xAranaktu** [comment]
Only v23.1.0.8 or newer works with Title Update 4

**Comment by chrisakmen** [comment]
23.1.0.8? where can i download that? when I look I can see max 23.1.0.5

**Comment by xAranaktu** [comment]
[Release Schedule For FIFA 23 Projects](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=0)
