### ISSUE TITLE
CreateProcess Failed

### ISSUE THREAD

**Issue by novanzhafran** [xAranaktu/FIFA-23-Live-Editor#120]
I've tried using the live editor. still can not. it say "CreateProcess Failed: the request operation requires operation"
can anyone help? 
![WhatsApp Image 2023-04-21 at 4 25 40 PM](https://user-images.githubusercontent.com/131446813/233600166-3fd69c79-8805-43d3-91f3-231be91e52ee.jpeg)

**Comment by xAranaktu** [comment]
#17

**Comment by AnthonyLoera** [comment]
> #17

No found
