### ISSUE TITLE
Using LE with internet

### ISSUE THREAD

**Issue by Furqan04** [xAranaktu/FIFA-23-Live-Editor#123]
I want to know it I'll get banned if I use LE with internet turned on. I've been playing FIFA 22 ever since AC stopped working for me. Can I use LE with internet turned on despite AC or is there another way to fix the issue?

**Comment by xAranaktu** [comment]
Yes, you can get banned for playing with Live Editor. Playing without internet also won't make you 100% secure, but it will reduce the chance slightly. There is no fix. Nothing can be done with that. If you are scared of getting banned then don't use live editor, cheat table or any kind of mods.
