### ISSUE TITLE
Game crashes if starting with LE , DirectX error

### ISSUE THREAD

**Issue by shd1ve** [xAranaktu/FIFA-23-Live-Editor#131]
![image](https://user-images.githubusercontent.com/132010946/234971591-ffe6cb85-0e71-48c9-ae50-446a6875bacc.png)

it's normal when i start the game in steam...shouldn't be GPU driver problem i guess?
pls help thanks

**Comment by xAranaktu** [comment]
Can be caused by the mods you are using or 3rd party overlays that you have installed.

**Comment by ffsiq** [comment]
everytime i try to run the game with LE it launches then crashes immediately but i dont get any errors
