### ISSUE TITLE
Fake EA Anticheat Launcher is running the game without the EA Anticheat Error

### ISSUE THREAD

**Issue by atef47** [xAranaktu/FIFA-23-Live-Editor#147]
![Capture d'écran 2023-05-14 013035](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/41908107/8da2d3f7-08a7-4ad0-8199-32d670342300)

hi Guys here is my probleme any help pls !

Fake EA Anticheat Launcher is running the game without the EA Anticheat
[+] Bypassing the Anticheat
[+] Args (1):

FIFA23.exe

[-] CreateProcess failed, error code 740
[-] LÆopÚration demandÚe nÚcessite une ÚlÚvation.
[-] Trying 'runas'...

**Comment by xAranaktu** [comment]
#17

**Comment by atef47** [comment]
No man it's still the same by the way i have windows 11 nothing change i run it as an Administrator @xAranaktu  any other methode ?

**Comment by xAranaktu** [comment]
**DON'T** run the game as administrator.

**Comment by khai1210** [comment]
i have this issue too, (Fake EA Anticheat Launcher is running the game without the EA Anticheat) but can't find the way. Can u help me ?

**Comment by atef47** [comment]
@xAranaktu ok the error is gone but the new probleme is the game crash in loading Screen i tried to change the delay time but still the same
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/41908107/444594a9-f1c1-4138-b378-1b5ad6254ac7)
