### ISSUE TITLE
Problem about the EA app

### ISSUE THREAD

**Issue by GotGimhong** [xAranaktu/FIFA-23-Live-Editor#15]
Hi xAranaktu, I've bought fifa23 from Steam. Everytime when I launch fifa23 through Steam, the EA app is then launched, and fifa23 won't started until the EA app is connected to server.

I'm clear that your live editor and cheat table are suggested to be run offline. But here is the problem, fifa23 fails to launch since the EA app is unable to connect to server, although the fake EAAC successfully runs.

Is there a proper way to skip the launching of EA app or just run it offline? Look forward to your favourable reply~

**Comment by xAranaktu** [comment]
I don't know any way to run the game without EA App.

**Comment by GotGimhong** [comment]
> I don't know any way to run the game without EA App.

All right, did you mean it's a way to run EA app offline? As you suggested running fifa23, including Steam and Origin offline.

**Comment by xAranaktu** [comment]
![](https://answers.ea.com/t5/image/serverpage/image-id/36805i1EC68132C8ACB705/image-size/original?v=1.0&px=-1)

**Comment by GotGimhong** [comment]
Ahhhhhh how careless I was. Thank you very much!
