### ISSUE TITLE
Issue with FIFA 23 Live Editor v23.1.2.6

### ISSUE THREAD

**Issue by JoeyGar** [xAranaktu/FIFA-23-Live-Editor#153]
To summarize, I tried launching the game using the Live Editor, the recent one that works with Title Update 12, and I got this error.

[+] Fake EA Anticheat Launcher is running the game without the EA Anticheat
[+] Bypassing the Anticheat
[+] Args (1):

FIFA23.exe

[-] CreateProcess failed, error code 740
[-] The requested operation requires elevation.
[-] Trying 'runas'...

on the command prompt, and I also got another one saying

'CreateProcess failed. The requested operation requires elevation'

And right after closing that, another one appears saying 'CreateProcess failed. FIFA23.exe'

I'd appreciate some help with this since I was waiting so long for this to come out only for it to not work, thanks. 👍

**Comment by xAranaktu** [comment]
#17
