### ISSUE TITLE
Loan Feature

### ISSUE THREAD

**Issue by fotis444** [xAranaktu/FIFA-23-Live-Editor#16]
When I try to loan a player to a specific team using the editor the game crashes.. Is there any way to work around it ?

**Comment by xAranaktu** [comment]
Which team, which player, which mode?
Also, attach live editor log files and latest fifa crashdump.

**Comment by IshanChakrabortyYT** [comment]
@xAranaktu Happened to me when I tried to transfer James Justin to Chelsea and Ronaldo to Real Madrid the game crashed... & I am playing as the manager career mode for FC Barcelona... I think there is some issue here Please look into this I already created one issue linking it here ...  #21 Please Look into this @xAranaktu
