### ISSUE TITLE
The requested operation requires elevation

### ISSUE THREAD

**Issue by kwiqi** [xAranaktu/FIFA-23-Live-Editor#169]
Every time I press Run Game , it says this

[+] Fake EA Anticheat Launcher is running the game without the EA Anticheat
[+] Bypassing the Anticheat
[+] Args (1):

FIFA23.exe

[-] CreateProcess failed, error code 740
[-] The requested operation requires elevation.
[-] Trying 'runas'...

**Comment by xAranaktu** [comment]
#17
