### ISSUE TITLE
Fake EEAC Launcher got CreateProcess failed (740)

### ISSUE THREAD

**Issue by gutakk** [xAranaktu/FIFA-23-Live-Editor#17]
Hi, do you have any idea how to solve this? My Fifa 23 is Steam version
Thanks in advance

![Untitled](https://user-images.githubusercontent.com/29707647/204118214-c7603b9c-3f63-4bfe-ad68-8d687eb19b67.png)

**Comment by Nicholas3789** [comment]
I have the same error

**Comment by nikolai-wustovich** [comment]
I am as well, but I am using EA app. Reinstalled the game, reinstalled anticheat, reinstalled live editor.

**Comment by nikolai-wustovich** [comment]
@xAranaktu

**Comment by xAranaktu** [comment]
Go to your game installation dir -> right click on "FIFA23.exe" -> Properties -> Compatibility -> Uncheck "Run this program as an administrator"

![](https://i.imgur.com/ABvMAWb.png)
