### ISSUE TITLE
Cant launch FIFA with LiveEditor

### ISSUE THREAD

**Issue by DawTaa** [xAranaktu/FIFA-23-Live-Editor#171]
When the EAAntiCheatGameServicelauncher.exe tries to bypass the anticheat i have this error:
[-] CreateProcess failed, error code 740
[-] »╣ (in my language:)the requested operation requires elevation ˝.
[-] Trying 'runas'...
and then FIFA23 launches without LiveEditor.

**Comment by xAranaktu** [comment]
#17
