### ISSUE TITLE
Live Editor crash problem

### ISSUE THREAD

**Issue by snix18** [xAranaktu/FIFA-23-Live-Editor#178]
I was using the live editor to change a player's miniface, so i took an image and converted it to a dds file. When i selected it, my live editor and FIFA crashed. Now any time I try editing anything, i get this error 

![241299390-9a0aa6f0-eb45-4255-9e8b-fbd5ddca522c](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/134734589/49f2d481-ef2d-4aea-830c-e3b92a635bcb)

**Comment by xAranaktu** [comment]
You have converted the miniface to wrong dds format (or maybe the size is wrong).
Read https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Importing-Miniface
