### ISSUE TITLE
I cant launch the game ("No game found after 1200 attempts")

### ISSUE THREAD

**Issue by Xarisvaf** [xAranaktu/FIFA-23-Live-Editor#179]
Can someone help ?
![Error](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/134742827/a59a4142-a734-4dc2-af6e-79b2fce7520f)

**Comment by xAranaktu** [comment]
Move live editor to location that contains only English characters

**Comment by Xarisvaf** [comment]
I moved it, turned off the antivirus and it works now.... thank u so much <3
