### ISSUE TITLE
Career mod question

### ISSUE THREAD

**Issue by Nerauh76** [xAranaktu/FIFA-23-Live-Editor#18]
Hello to you, I created a pro for my solo career on fifa and when I modify the stats it puts them back as before after a training or sometimes match, is this normal?

**Comment by gabrieldsw** [comment]
i have same problem

**Comment by xAranaktu** [comment]
You can't edit most of the things in player career mode when you play as created play. The game design doesn't allow for this. The only way to upgrade your player attributes in that mode is the [999 skill points](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/999-Skill-Points) cheat that you can find in the [cheat table](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table)
