### ISSUE TITLE
Team name editor not working 

### ISSUE THREAD

**Issue by SurfBlade1** [xAranaktu/FIFA-23-Live-Editor#186]
After changing a team name in database editor and saving the changes, it does not apply in game. I have also restarted the game and is still does not apply, Please let me know if you have a solution to this. Thank you.

**Comment by xAranaktu** [comment]
The game isn't using the `teamname` that you can find in `teams` table. To change the name you need to edit loc db (not with LE).
[This video ](https://www.youtube.com/watch?v=4oSchcttxTo) shows how to change team name
