### ISSUE TITLE
Editing Players Issue

### ISSUE THREAD

**Issue by harry0511** [xAranaktu/FIFA-23-Live-Editor#198]
When I edit my career mode player and change his stats using live editor and cheat engine as soon as I advance time or train his stats reset. How do I stop this ?

**Comment by xAranaktu** [comment]
That's how the game is designed nothing can be done with that.
The only way to make your players better is the [999 skill points script](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/999-Skill-Points)
