### ISSUE TITLE
My textures are loaded incorrectly or are an error

### ISSUE THREAD

**Issue by Wojbarley** [xAranaktu/FIFA-23-Live-Editor#199]
My textures are loaded incorrectly or are an error and this is what it look 
![texture bug le fifa 23](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/137000773/1f7e950f-7c28-468f-bb72-d2abe4194670)
(and i use EEP23 By Viper and 23/24 Kits mod i don't now is it it?)

**Comment by xAranaktu** [comment]
This happens to AMD GPU users. I don't know why and I don't know the solution.
