### ISSUE TITLE
Ea games anti cheat live edit

### ISSUE THREAD

**Issue by mreess1** [xAranaktu/FIFA-23-Live-Editor#201]
I'm playing fifa 23 via ea games because of this, ea anticheat also opens, will I get banned if I use the live editor?

**Comment by AYOUBZOBI568** [comment]
Sorry

في الثلاثاء، 20 يونيو، 2023 10:22 م mreess1 ***@***.***> كتب:

**Comment by xAranaktu** [comment]
If original anticheat starts then live editor isn't working, so no, you won't get banned.
