### ISSUE TITLE
After last update "women's world cup" Live editor stop working.

### ISSUE THREAD

**Issue by Bamsi1337** [xAranaktu/FIFA-23-Live-Editor#205]
After last update "women's world cup" Live editor stop working. When i running FIFA 23 live editor just crashing without errors or smthing....

**Comment by xAranaktu** [comment]
In TU14 EA has changed the boot flow sequence for some reason and because of that the Live Editor is not able to figure out that it has reached the main menu and because of that the tool doesn't finish initialization.
But it's not a big problem to fix, will be fixed v23.1.2.9 today.

**Comment by xAranaktu** [comment]
[v23.1.2.9](https://www.patreon.com/posts/85198350) has been released for Patrons.
Public release on 4th July 2023

**Comment by yarozzi** [comment]
please, release it  here so we can use too

**Comment by mrdecas** [comment]
same

**Comment by jonmacarsen** [comment]
1.3.1 same
