### ISSUE TITLE
Since new fifa update the overlay wont show

### ISSUE THREAD

**Issue by domasel** [xAranaktu/FIFA-23-Live-Editor#208]
Since this new update when i start the live editor like always it just doesnt show up. I tried everything, Anyone else got the same problem or

**Comment by enskksl** [comment]
I have that same problem

**Comment by domasel** [comment]
Okay so its not just me good

**Comment by xAranaktu** [comment]
#205

**Comment by le3b** [comment]
yup same here. I hope xAranaktu releases a new version which addresses this issue

**Comment by olszabyk** [comment]
I also have that problem

**Comment by xAranaktu** [comment]
Just check #205 (-_-)

**Comment by kalojam** [comment]
bro update where :(

**Comment by mrdecas** [comment]
same
