### ISSUE TITLE
Game doesn't go further than the starting screen - Patreon Version

### ISSUE THREAD

**Issue by finlaytait** [xAranaktu/FIFA-23-Live-Editor#210]
Since newest update the game freezes at 'FIFA 23' Splashscreen

**Comment by xAranaktu** [comment]
send log files.

**Comment by xAranaktu** [comment]
Can you even run the game without LE? As you are starting the game with mods that most likely aren't update then that's probably the issue which makes your game not start, not LE.

**Comment by finlaytait** [comment]
Nevermind it's just fifa. 
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/137923392/10ed6687-e6a5-4680-ab25-18a4be9a4e4a)
 here's the memory dump 
https://drive.google.com/file/d/1rpCa99HJ9aFgoBiM9ngwHBnwq1Ohu238/view?usp=sharing

**Comment by Cinder9000** [comment]
> Since newest update the game freezes at 'FIFA 23' Splashscreen

i had that because on game launch settings i have the "-dataPath FIFAModData" that was freezing the game from me on launch screeb after take -dataPath FIFAModData the game works fine
but the live editor and all mods i have dont work anymore....

**Comment by finlaytait** [comment]
Works with newest patreon version
