### ISSUE TITLE
Live Editor Failed

### ISSUE THREAD

**Issue by DeseNutzz** [xAranaktu/FIFA-23-Live-Editor#218]
No game found after 1200 attempts
PID:18428 STATUS: OK
PID:21268 STATUS:OK
PID: 23540 ERROR: UKNOWN
PID:24744 STATUS OK

**Comment by Oliverhedstrom** [comment]
i have the same issue

**Comment by jawaradigital** [comment]
CARANYA : 
Buka APP STEAM
Matikan Koneksi Internet setelah STEAM terbuka
Klik STEAM => GO OFFLINE
Buka LE nya trus RUN game nya dari STEAM

Pastikan udah setting -dataPath FIFAModData biar run dari STEAM pun MOD nya ngikut (JIKA PAKAI MOD).

kalau dah nyoba bs tinggalkan jejaknya bang hehe

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
