### ISSUE TITLE
fifa 23 live editor no game found after 1200 attempts

### ISSUE THREAD

**Issue by Maciejowskiv1** [xAranaktu/FIFA-23-Live-Editor#221]
help me please, Live editor not working. When I launch the Live Editor I got a message "fifa 23 live editor no game found after 1200 attempts"

**Comment by PlutoDoFifa** [comment]
I'm having the same issue. Don't know if it has something to do that LE is outdated, bc it was updated 4 days ago and fifa got an update later after LE was updated. I can be wrong, idk I'm just guessing

**Comment by LAj415** [comment]
Same here.

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
