### ISSUE TITLE
Launcher wont start since 4 days 

### ISSUE THREAD

**Issue by xxxShinez** [xAranaktu/FIFA-23-Live-Editor#222]
Since i think 3to4 days i cant start the editor.
i downloaded the new version 5 mins ago and it still dosnt work

![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138371494/df1aa06a-3c6a-4d96-9b33-205397594cbc)

that happens and after that nothing happens
when i try to press start launcher 
it says it cant be started twice

![Fifa Editor Screenshot](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138371494/b854caa4-7054-463d-a472-8e014c6419ef)

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
