### ISSUE TITLE
Live Editor version 23.1.2.8 won't open

### ISSUE THREAD

**Issue by Nikkeb22** [xAranaktu/FIFA-23-Live-Editor#225]
When i launch the game from the EA app the live editor launcher doesn't pick it up and when i start the game from the LE launcher nothing happens, it just sends this error 

https://cdn.discordapp.com/attachments/783749771696406608/1125084974513655869/image.png

**Comment by zzlyz** [comment]
pretty sure its cos game was updated so i think we need to wait for next update on LE

**Comment by hiqewzz** [comment]
I have the same issue. pretty sure we have to wait for next update

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
