### ISSUE TITLE
The game opens and closes directly with Live Editor

### ISSUE THREAD

**Issue by Yogorasi** [xAranaktu/FIFA-23-Live-Editor#227]
Hello,

When I want to launch my game with Live Editor, I switch on Live Editor and whether I select "run game" or switch on the game directly with the launcher, the game switches on and then switches off again. What's more, even if I restart my computer or uninstall Live Editor, the game still launches with it (files in the Fifa 23 root folder).

So I'm trying to fix this by repairing my game via the EA launcher, but in any case I can't use Live Editor any more. Is this because of the new Fifa updates?

Thanks a lot!

**Comment by zzlyz** [comment]
its due to an update pretty sure, for all i know it might not be but it stopped working for me and does the same thing you described straight after the update.

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
