### ISSUE TITLE
No Game found after 1200 attempts / PID: 16028 STATUS: Ok

### ISSUE THREAD

**Issue by Shecallsmedaviid** [xAranaktu/FIFA-23-Live-Editor#229]
The Error is in the Title, cant figure out how to fix it. 
I selected the correct game folder, and as soon as I press "Run Game" everything looks normal, but as soon as the "Fake EA Anti cheat" window comes up, after that nothing happens and it throws me back into the EA Launcher. And after a while, this error comes.

![Fail2](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138406425/f70a05d3-44e6-448e-961c-887d6d3263e0)
![Fail1](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138406425/47cb2311-282c-42fe-a30b-b01f2a70864a)

**Comment by yudaduta** [comment]
Have you tried restart LE, and then running it again as admin?
I have experienced it, but restart LE and running as admin solved the issue for me.

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.
