### ISSUE TITLE
Live Editor won't launch the game

### ISSUE THREAD

**Issue by westfp** [xAranaktu/FIFA-23-Live-Editor#231]
So I am a relatively new user to the Live Editor and first used it about two weeks ago. Since then I have not used it at all and no one else who has used my computer has done anything with it. It worked as intended when I first used it. However since I have got back when I press 'Run Game' it brings up a black screen with writing on it and I have not been able to use the Live Editor on the game at all. I am not sure if there is something I should do. I have looked up steps online however none of them contain the black screen I am facing. I also had a big problem with the game not launching when not using the Live Editor and had to seek help on the EA Live Chat and so perhaps something that they told me to do has prevented the Live Editor from doing what it is intended to do. When I turn off the WiFi and disconnect my Ethernet cable the EA app says that I have lost connection which makes sense, however the EA app when I first used the Live Editor did not bring up the EA app. Hopefully someone can understand what is going on with my Live Editor and they can help me fix it. Thanks Very Much
![Live Editor Broken](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138503188/8bfeeb07-000d-42cb-bfda-079856eb5fb9)

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1. 
Also, [don't run the game as admin](https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Troubleshooting)

**Comment by westfp** [comment]
What does TU 14.1 mean? Also I went into properties and made sure it doesn't run as an admin however it still has the blue and yellow shield sign (admin sign) what should I do.

**Comment by xAranaktu** [comment]
TU stands for Title Update. 14.1 was released a few days ago.
