### ISSUE TITLE
the graphics are corrupted

### ISSUE THREAD

**Issue by AntonioCr95** [xAranaktu/FIFA-23-Live-Editor#233]

**Comment by AntonioCr95** [comment]
Can anyone tell me why the LIVE EDITOR graphics appear like this?

![0ED63B44-70E1-440D-A42C-A15B113B337F](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138537151/8f57b3c0-fb88-45f3-a904-a505968891d2)

**Comment by xAranaktu** [comment]
#199

**Comment by AntonioCr95** [comment]
what does this number mean?

**Comment by AntonioCr95** [comment]
is there no solution?😭
