### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pavlozz2s** [xAranaktu/FIFA-23-Live-Editor#234]
The Live Editor is not working for me. Cannot log into the game. Without starting an Live Editor its working.

**Comment by freirezin666** [comment]
the same thing is happening to me

**Comment by JamieGHG** [comment]
It's because Fifa got a update, but not the editor, but today he should put the new update online for everyone.

**Comment by pavlozz2s** [comment]
Yes, the Anticheat had a update i think

**Comment by Kozlowski213** [comment]
Are you sure there will be a new update today?

**Comment by mekh1ii** [comment]
samething is happening to me but when I run the launcher it restarts the EA app and the game doesnt open.

**Comment by pavlozz2s** [comment]
It is the same thing as me. I hope that the new update fix will fix it

**Comment by Kozlowski213** [comment]
me too

**Comment by xAranaktu** [comment]
Only [v23.1.3.1](https://www.patreon.com/posts/85306656) is working with TU 14.1.

**Comment by mekh1ii** [comment]
so when is it releasing free.
