### ISSUE TITLE
When is 1.3.1 becoming free

### ISSUE THREAD

**Issue by mekh1ii** [xAranaktu/FIFA-23-Live-Editor#236]

**Comment by lianoxxx** [comment]
how do you guys get 1.3.1?????

**Comment by mekh1ii** [comment]
> how do you guys get 1.3.1?????

Bro I js asked when is 1.3.1 releasing meaning when is it becoming free. If you really want it go on his patreon and buy it .

**Comment by lianoxxx** [comment]
yea i just checked it is not free, it's really gonna be free?? i mean it's look like not going to be free

**Comment by xAranaktu** [comment]
6th July 2023, 4:30 PM CEST [Release Schedule](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=0)
