### ISSUE TITLE
Live Editor can't creat directories

### ISSUE THREAD

**Issue by Cauw006** [xAranaktu/FIFA-23-Live-Editor#24]
Because of that it's impossible to use some features like generate minifaces - and probably others I didn't test yet.
Thanks for listening

![image](https://user-images.githubusercontent.com/114539344/205925774-da6daa72-29b5-473e-8bde-2e5665cb9c42.png)

**Comment by Javo2205** [comment]
same error, could you solved?

**Comment by xAranaktu** [comment]
Change live editor mods directory in live editor settings. Use folder that doesn't require admin rights for writting and reading. For example you can create new folder on C: drive and call it "Live Editor Mods" and use it as your new LE mods folder.

**How to change Live Editor Mods Directory?**
Run the game with live editor and while in main menu press F9 to show it. Then in top left corner click on Windows -> Settings, in settings open "Directories" and change root directory for live editor mods. Make sure you have picked destination that contains only UTF-8 characters and it doesn't require admin rights for reading & writing.

![](https://i.imgur.com/IdAqWwG.png)
