### ISSUE TITLE
LE won't show up in the Fifa menu

### ISSUE THREAD

**Issue by Upab** [xAranaktu/FIFA-23-Live-Editor#25]
Hello! the issue is I followed all of the step, but every time I open the live editor from the launcher it could open the fifa 23 but the live editor doesn't show up in the menu, even when I pushed the alt+F9. 

Please if you have any solutions, I will happy to hear.

**Comment by ByYasin** [comment]
Likewise, the menu does not appear, there is no injecte problem in the logs.

**Comment by Upab** [comment]
Thank you! Anyway do you have any solutions for that live editor problem?

**Comment by kamski4998** [comment]
i have the same problem
