### ISSUE TITLE
Live editor is not opening

### ISSUE THREAD

**Issue by Maxdack258** [xAranaktu/FIFA-23-Live-Editor#250]
I was newer versions of live editor until I got out of the game to add mods. Afterwards, live editor wouldn´t open, it would just show up the warning message but when I clicked "Ok" the live editor didn´t open. I tested a much older Live editor version and it worked, but I don´t understand why the newer versions would´nt work

**Comment by xAranaktu** [comment]
Hard to say without logs. Perhaps launcher crashes when it tries to read settings from `C:\FIFA 23 Live Editor\config.json`, so delete the `config.json`

**Comment by Maxdack258** [comment]
Wow thanks man it worked!
