### ISSUE TITLE
End loan

### ISSUE THREAD

**Issue by allen-ting** [xAranaktu/FIFA-23-Live-Editor#26]
This is not a issue for your great work, it's just a wish of mine.

I played career mode only and sometime I found perfect player for my squad but sadly he's already loan out.
Is there a "end loan" option already? (please help me find it)
or any chance to have one in future update?

**Comment by xAranaktu** [comment]
There is already an option allowing you to terminate loans
![](https://i.imgur.com/s5SqoUm.png)

**Comment by allen-ting** [comment]
Thanks!
