### ISSUE TITLE
Manager Age career mode

### ISSUE THREAD

**Issue by Cinder9000** [xAranaktu/FIFA-23-Live-Editor#266]
It is possible to change the age of the manager, I want to continue the save I have but my manager is going to retire, and I would like to continue this save, i try to search a way on the live editor but i could not find it

**Comment by xAranaktu** [comment]
You can try to change seasoncount to 1 in career_users table with RDBM. If that doesn't work then there is no other way.

**Comment by Cinder9000** [comment]
> You can try to change seasoncount to 1 in career_users table with RDBM. If that doesn't work then there is no other way.

i try didn't work, i appreciate the help anyway
