### ISSUE TITLE
Live Editor Issue with EA App and Mod Manager

### ISSUE THREAD

**Issue by p34nk** [xAranaktu/FIFA-23-Live-Editor#27]
Having issues running Live Editor (1.1.3) with EA App (as it forced me to switch from Origin. It was fine working with Origin prior to December) and running through Mod Manager (v. 1.1.3). In the command line I saw an error not previously seen when using Origin (as shown in screenshot). 

EA App then said the game is already running, and I got error message from Live Editor: Failed: No game found after 0 attempts. PID: 2104 STATUS: OK.

Any help will be appreciated.
![image](https://user-images.githubusercontent.com/120191258/206720017-2ade77cc-1f23-4582-afbd-5efef71d3038.png)

Could it be related to the error message with elevated permission related? Do I need to run something as admin? Seems the LE failed to detect the game being ran or something.

**Comment by xAranaktu** [comment]
First of all try to add add `-dataPath FIFAModData` in `Advanced Launch Option` as mentioned in [Getting Started](https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Getting-Started) guide if you didn't done it before.

If that won't work then try to change the injection delay (`300/500/1000/2000/3000/5000/7000/10000`). If that also won't work then try older versions of the live editor launcher (v23.1.0.8 or newer)

**Comment by mlotix** [comment]
Problem was fixed for me when I launched FIFA 23 without "run as administrator" checked.
