### ISSUE TITLE
Is there a way to increase the number of players in the team?

### ISSUE THREAD

**Issue by davidrock** [xAranaktu/FIFA-23-Live-Editor#272]
I remember seeing these options in old Career Tables. I invested in many players thinking of trading them later but I have reached the maximum of players in my team.

**Comment by xAranaktu** [comment]
Max squad size if unfortunately hardcoded and can't be changed without rewriting half of the game. I don't think it was ever an option in any of my cheat tables, but even if then I probably quickly removed it when I realized it's an easy way to break your career save. Afaik. there are mods out there which says that they change the limit and from what I saw all these mods were doing is changing the `MAX_SQUAD_SIZE` in `cmsettings.ini`.  So you can edit that file by yourself (even with live editor -> File Browser), or you can search the internet for that kind of mod, but as I said I'm 99.9% sure that sooner or later this change will completely brick your career save.
