### ISSUE TITLE
Live editor menu not appearing in game

### ISSUE THREAD

**Issue by dandyx54** [xAranaktu/FIFA-23-Live-Editor#280]
When i open fifa Live editor menu is not appearing in game

**Comment by xAranaktu** [comment]
send live editor log files

**Comment by dandyx54** [comment]
> send live editor log files

How to find them?

**Comment by dandyx54** [comment]
> send live editor log files

the log files

**Comment by dandyx54** [comment]
> send live editor log files

how can i find them?

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Frequently-asked-questions

**Comment by xAranaktu** [comment]
> This is it?

Yes.

Live Editor v23.1.3.2 and older (probably) doesn't work with Title Update 15. 
You need [FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)

Public release on:
Jul 26, 2023 at 3:30 PM CEST

**Comment by dandyx54** [comment]
> > This is it?
> 
> Yes.
> 
> Live Editor v23.1.3.2 and older (probably) doesn't work with Title Update 15. You need [FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)
> 
> Public release on: Jul 26, 2023 at 3:30 PM CEST

so on 26 it will work?
