### ISSUE TITLE
Live Editor v23.1.3.2 won't launch FIFA

### ISSUE THREAD

**Issue by westfp** [xAranaktu/FIFA-23-Live-Editor#283]
The same black page that shows up when it is bypassing the anticheat shows as normal and it says [OK+] however the game doesn't launch?

**Comment by Luciferr00** [comment]
i think cause fifa just update their game so the live editor doesn't work this time

**Comment by xAranaktu** [comment]
#281 
Live Editor v23.1.3.2 and older (probably) doesn't work with Title Update 15. 
You need [FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)

Public release on:
Jul 26, 2023 at 3:30 PM CEST
