### ISSUE TITLE
On steam it shows me that the game is running, but it doesn't work

### ISSUE THREAD

**Issue by Fildoook** [xAranaktu/FIFA-23-Live-Editor#285]

**Comment by xAranaktu** [comment]
#281 
Live Editor v23.1.3.2 and older (probably) doesn't work with Title Update 15. 
You need [FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)

Public release on:
Jul 26, 2023 at 3:30 PM CEST
