### ISSUE TITLE
Live Editor DirectX issue

### ISSUE THREAD

**Issue by pavlozz2s** [xAranaktu/FIFA-23-Live-Editor#288]
Hello. I have a issue. When i try to edit player in a Live Editor, it says to me this error: 
![obrázek_2023-07-22_215813464](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138609531/2f5ce965-eb4c-43f5-93f9-8bb50b60cc9d)

**Comment by xAranaktu** [comment]
Disable loading images in live editor settings.
