### ISSUE TITLE
Fifa not launching through Live editor 

### ISSUE THREAD

**Issue by Zain2001044** [xAranaktu/FIFA-23-Live-Editor#290]
Every time I try to launch the game through the live editor it doesn't launch. The live editor keeps on saying "injecting" and the game is not running. 
It happened after the new title update. When will the new live editor be released publicly?

**Comment by xAranaktu** [comment]
#281 
Live Editor v23.1.3.2 and older (probably) doesn't work with Title Update 15. 
You need [FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)

Public release on:
Jul 26, 2023 at 3:30 PM CEST
