### ISSUE TITLE
Player career mode changes not sticking

### ISSUE THREAD

**Issue by AnakinDripwalker** [xAranaktu/FIFA-23-Live-Editor#297]
Hi,

I have an issue since some weeks ago, when I edit my career player it works as intended, I even can play a match with these stats.

But when I save my career and come back, or when I finish a match, the stats are back like before the changes.

Also I use LE 1.3.3 (last version)

It was working in January, but when I came back in like July id didn't work anymore.
The only change that occured in the meantime is that I switched from Origin to EA App.

If anyone could help me it would be appreciated :)

**Comment by maupotjuhh** [comment]
I have the same thing.. Everytime i do a career mode and exit the game and come back after, lets say i coach liverpool and rebuild it like crazy. I come back with the starter team, even though i changed the squadfile to the real life transfers. So no idea why it does that. I have the same aswell with normal fifa.

**Comment by AnakinDripwalker** [comment]
Oh I'm quite satisfied to see I'm not alone in this case. I really struggled to find similar cases on the live editor 23, but I still don't know why, changes can't save even when changing LE directory or executing as administrator...

**Comment by xAranaktu** [comment]
It's like that since years... The way the game is designed doesn't allow you to do permanent changes in created player career mode.

**Comment by AnakinDripwalker** [comment]
So it's not possible ? Damn I remember using the ct too to edit my player (for skill points and attributes) and others as well in career, but maybe I didn't directly modify my player stats... No 99 for my player :/
