### ISSUE TITLE
Your files need repairing 

### ISSUE THREAD

**Issue by Javierlolcx** [xAranaktu/FIFA-23-Live-Editor#3]
I've already repaired the files multiple times and edited them over and over, but it still says the same thing. any help and how to get it to work and not say my files need to be repaired?

**Comment by Spontaneously** [comment]
Same

**Comment by xAranaktu** [comment]
Use Origin or Live Editor v23.1.0.3+

**Comment by sidomapui07** [comment]
> Use Origin or Live Editor v23.1.0.3+

where do i get Live Editor v23.1.0.3?

**Comment by xAranaktu** [comment]
https://www.patreon.com/posts/fifa-23-live-v23-73764369

**Comment by sebastiankhoa** [comment]
> https://www.patreon.com/posts/fifa-23-live-v23-73764369

Yes, you must pay 1$ for this ,lol
