### ISSUE TITLE
Game crashed when using Players Editor

### ISSUE THREAD

**Issue by allen-ting** [xAranaktu/FIFA-23-Live-Editor#30]
LE version: v23.1.1.0
Game mode: Career mode (Manager)

Crash situation 1
1. Player Editor Window for a selected player
2. Drop down list of "Player" button
3. Import/Generate Miniface successfully
4. Crash right after press "Delete Miniface" button

Crash situation 2
1. Player Editor Window for a selected player
2. Drop down list of "Player" button
3. Crash right after press "Release From Team" button

**Comment by IshanChakrabortyYT** [comment]
> LE version: v23.1.1.0 Game mode: Career mode (Manager)
> 
> Crash situation 1
> 
> 1. Player Editor Window for a selected player
> 2. Drop down list of "Player" button
> 3. Import/Generate Miniface successfully
> 4. Crash right after press "Delete Miniface" button
> 
> Crash situation 2
> 
> 1. Player Editor Window for a selected player
> 2. Drop down list of "Player" button
> 3. Crash right after press "Release From Team" button

I am having the same issues when I am transferring a Player to another club the game is getting crashes. #21 
@xAranaktu Any idea whats going on with the crashes also the txt file is not giving any idea about it why it's getting crashed.

**Comment by xAranaktu** [comment]
The only idea I got about crashes related to player transfers if the fact the LE is trying to reload club crest. So, you can try to disable loading images in live editor settings and see if it works. If not then I don't have any other solution.

**Comment by IshanChakrabortyYT** [comment]
@xAranaktu There are any Celebration ids list ?? if Please can you share with us
