### ISSUE TITLE
Fifa 23 crashes when loading into a match

### ISSUE THREAD

**Issue by gmannthegreat68** [xAranaktu/FIFA-23-Live-Editor#306]
- i'm only a season or 2 into the career. 
- crashes when it goes onto the black screen before showing the cinematic that begins with the goal net.
- i've reloaded and retried to play numerous times but it crashes at the same point every time
- i've only edited a few players' stats with cheat engine
- i've tried with and without cheat engine
- the boot up with the fake anticheat is all good and normal

**Comment by xAranaktu** [comment]
Your career is corrupted. Start new one.
