### ISSUE TITLE
Crashing when editing players created by another mod

### ISSUE THREAD

**Issue by aaronxxii** [xAranaktu/FIFA-23-Live-Editor#308]
The game crashes whenever I edit a player added to the game by another mod.
For example, if I want to edit Cristiano Ronaldo using the Live Editor, it's possible because he's in the vanilla game.
If I try to edit Bibras Natcho (Partizan), added by the EEP mod, the game crashes and it says the following message:
![directx function](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/140840450/3d7979b4-6a59-427b-8ef0-86d7ab61041f)

DirectX function "GetDeviceRemovedReason" failed with DXGI_ERROR_INVALID_CALL.

**Comment by xAranaktu** [comment]
There are some invalid crests in EEP. Not live editor issue. You can disable loading images in live editor settings to bypass this problem.
