### ISSUE TITLE
No Game Found After 0 Attempts.

### ISSUE THREAD

**Issue by nikolai-wustovich** [xAranaktu/FIFA-23-Live-Editor#31]
You don't have a troubleshooting section for this one. So, what should I do?

![Screenshot (42)](https://user-images.githubusercontent.com/119711014/207475562-adbd9f7f-46ea-41e1-a156-a94f9199a83a.png)
![Screenshot (43)](https://user-images.githubusercontent.com/119711014/207475569-3cb4f455-3509-47eb-92f9-de0b24937f63.png)

**Comment by EvilAsDevil** [comment]
same problem here :(

**Comment by EvilAsDevil** [comment]
i had the same problem and it turned out it is from Origin it self. i kept logging in and out (from Origin app not LE Launcher) untill the game popped up for me

**Comment by nikolai-wustovich** [comment]
@xAranaktu

**Comment by xAranaktu** [comment]
No known fix for this.

**Comment by Ricaedosi** [comment]
i have the same problem

**Comment by Ricaedosi** [comment]
have like 1 month with this problem, pls can anyone help me please?

**Comment by vqmxza** [comment]
hey man, i don't know if this can help you, but my solution with this problem was this: open the folder where fifa is installed and click on the properties of the folder, go to the security tab and enable the access of every user and group by putting on every check .
