### ISSUE TITLE
How to change player specific voicelines/animations

### ISSUE THREAD

**Issue by El3ctroe** [xAranaktu/FIFA-23-Live-Editor#312]
How do I change voicelines and animations that are specific to a certain player? Voicelines as in like "OOOOH! WHAT AN INCREADIBLE SAVE BY COURTOIS" instead of "and saved by the keeper" or just generally the last name used by the commentators. Both ideally.
Animations like Ronaldinho's scoring dance.

Could this be done by implementing a copy player feature or something like that or are these specific voicelines hardcoded to a player id? Thanks.

**Comment by xAranaktu** [comment]
Commentary name can be assigned/changed by editing commonnameid or lastnameid, but it doesn't always work.

Goal celebrations as far as I remember can be changed by editing `finishingcode1` / `finishingcode2`, but some are probably hardcoded to playerid.
