### ISSUE TITLE
When is the public release for FIFA 23 Live Editor v23.1.3.4?

### ISSUE THREAD

**Issue by Jayden0907** [xAranaktu/FIFA-23-Live-Editor#316]

**Comment by xAranaktu** [comment]
[Live Editor Release Schedule](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=0)

**Comment by Onny-Bet** [comment]
When is the public release for FIFA 23 Live Editor v23.1.3.4 CAN'T LAUNCH THE GAME ANYMORE IT REQUIRES FIFA 23 Live Editor v23.1.3.5 OR LATEST
