### ISSUE TITLE
Won’t run

### ISSUE THREAD

**Issue by Cripticbeats** [xAranaktu/FIFA-23-Live-Editor#32]
Keeps saying no game found after 1200 attempts
![Uploading image.jpg…]()

**Comment by nikolai-wustovich** [comment]
Yeah, had same problem. He responded with "no known fix for this". Guess I'm not using his programs this time around.

**Comment by Cripticbeats** [comment]
But must be doing something wrong because it works for other people starting to give up myself to be fair

**Comment by FelipeMorandini** [comment]
Did someone find a fix for this? Got the recent update that supposedly works for update 6, but i get this same error.

**Comment by fifabono** [comment]
me too. latest update 6 made us can not launch game using live editor

> Did someone find a fix for this? Got the recent update that supposedly works for update 6, but i get this same error.

**Comment by Elias-RGB** [comment]
@xAranaktu
