### ISSUE TITLE
Unable to open live editor

### ISSUE THREAD

**Issue by zorro6969** [xAranaktu/FIFA-23-Live-Editor#324]
can't open live editor because it couldn't find "MSVCP140.dll."
Then when i click ok it shows up "VCRUNTIME140.dll."
And then the first one again

![Skärmbild 2023-08-08 200016](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138833912/c14f2f7e-db37-4fd8-97a7-7a557d2e3b01)

**Comment by xAranaktu** [comment]
As google says, you need [vcredist](https://www.microsoft.com/en-gb/download/details.aspx?id=48145).
