### ISSUE TITLE
Cant start a Fifa with Live Editor

### ISSUE THREAD

**Issue by surfaros654CZ** [xAranaktu/FIFA-23-Live-Editor#330]
Hello, i cant start a fifa23 with a live editor. I have downloaded the latest version 1.3.6 from patreon and after i press the run game button, the EA Launcher starts and the game dont start, after then the error message "CANT FIND THE GAME AFTER 1200 ATTEMPTS" showed up. Help me please. Thank you

**Comment by xavifdzzz** [comment]
Same

**Comment by 19burak40** [comment]
same for me it won't open

**Comment by Neuroboy01** [comment]
same!

**Comment by MustafaSasaa123** [comment]
in order to play it use  fifa 23 Live Editor v23.1.3.6

**Comment by 19burak40** [comment]
> in order to play it use fifa 23 Live Editor v23.1.3.6

How? That version still has to come out. It looks like the latest version is 1.3.4.

**Comment by jfxrbes** [comment]
its out for patreon payers, public free release is on monday

**Comment by gajahkembar** [comment]
> Hello, i cant start a fifa23 with a live editor. I have downloaded the latest version 1.3.6 from patreon and after i press the run game button, the EA Launcher starts and the game dont start, after then the error message "CANT FIND THE GAME AFTER 1200 ATTEMPTS" showed up. Help me please. Thank you

u need the latest LE from xAranaktu, he will release in 21 Aug 2023
