### ISSUE TITLE
FIRST ARANAKTU AND ALL MOD USERS. PLEASE READ

### ISSUE THREAD

**Issue by YGTKMN** [xAranaktu/FIFA-23-Live-Editor#331]
Hello first of all..
I'M A PLAYER USING YOUR MOD FROM TURKEY AND I'M SURE THAT THERE ARE PEOPLE FROM MANY DIFFERENT COUNTRIES LIKE ME.
I CAN GUESS YOU MADE THIS MOD AFTER GREAT WORK.I HAVE BEEN USING THE MOD IN EVERY FIFA GAME FOR YEARS.MAN, $4.2 IS A LOT OF MONEY IN MY COUNTRY AND I CAN'T PAY IT EVERY MONTH.I KNOW THAT YOU MADE THIS MOD AS A RESULT OF WORK AND YOU SHOULD EARN FROM IT.I HAVE A CHANCE TO GIVE THIS ONE-TIME FEE YES.I WANT TO DONATE TO YOU BECAUSE I AM THE PERSON THAT ONLY PLAYS CAREER MODE IN THE GAME OF FIFA. ONLY THIS WAY I CAN ENJOY THIS GAME.YOU SHARE YOUR MOD HERE AND THE UPDATE IS COMING AFTER 2 DAYS AND WE CANNOT USE IT AGAIN FOR 2 WEEKS.THIS DESTROYS EVERYTHING.I'M SURE THERE ARE HUNDREDS OF PEOPLE WHO THINK LIKE ME WE LOVE YOUR MODES WE RESPECT YOUR WORK WE CAN UNDERSTAND YOU WANT TO MAKE MONEY AND BUT AS PEOPLE USING IT FOR FREE, WE HATE THE WAIT.I do not know your language very well, I used translation, I hope I was able to express myself and users who think like me.Respect and Love to All.

**Comment by SanderVincenzoO** [comment]
I can't make the payment to get silver! all cards fail ! Help @xAranaktu

**Comment by xAranaktu** [comment]
No one is forcing you to update the game. Especially if you only play career mode. [Disable auto updates, create copy of your game files](https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Game-Backup) and next time you will be able to continue playing with mods and LE if EA update the game.

**Comment by SanderVincenzoO** [comment]
good morning! I didn't say that I have to buy it, I'm saying that I wanted to buy it, but I can't! I asked for a solution, a support only!


Enviado do Yahoo Mail para iPhone


Em sexta-feira, agosto 18, 2023, 3:34 AM, Paweł ***@***.***> escreveu:




No one is forcing you to update the game. Especially if you only play career mode. Disable auto updates, create copy of your game files and next time you will be able to continue playing with mods and LE if EA update the game.

**Comment by xAranaktu** [comment]
> good morning! I didn't say that I have to buy it, I'm saying that I wanted to buy it, but I can't! I asked for a solution, a support only! 

I was replaying to OP, not your random question. 
Patreon is the only way to buy the access. Payments are processed by them too, not me. I can't help you with all kind of problems with payments. You need to contact with Patreon support or your bank or idk.
