### ISSUE TITLE
I can't open the game with the Live Editor, it always crashes

### ISSUE THREAD

**Issue by IndioJunior** [xAranaktu/FIFA-23-Live-Editor#335]
I open the Live Editor Launcher, I click on the run button to start the game with the live editor, the ea application opens and tries to open the game and it does not.
![Capturar](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/142720809/883a78e2-d37a-4766-8115-17b0ddbe8d52)
[log_20-08-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12387902/log_20-08-2023.txt)
[log_launcher_20-08-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12387903/log_launcher_20-08-2023.txt)

**Comment by xAranaktu** [comment]
Only [Live Editor v23.1.3.6](https://www.patreon.com/posts/87829285) is working with TU 17.1
