### ISSUE TITLE
Can´t find Fifa23.exe in:

### ISSUE THREAD

**Issue by kktmcjl** [xAranaktu/FIFA-23-Live-Editor#336]
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/142726799/b4deeb22-91a3-43ff-bae0-340b3dd7da79)
please help me

**Comment by yigittt07** [comment]
You must open FIFA 23 with Steam or Origin first. After than you can use LE to launch.

**Comment by xAranaktu** [comment]
Open live editor settings and manually select the game location 

![](https://i.imgur.com/A47zz33.png)
