### ISSUE TITLE
No game found

### ISSUE THREAD

**Issue by OoogaBoonga** [xAranaktu/FIFA-23-Live-Editor#337]
I get no game found after 1200 attempts, but PID 23536 status is ok, so is there something im doing wrong when running the game?

**Comment by xAranaktu** [comment]
Only [Live Editor v23.1.3.6](https://www.patreon.com/posts/87829285) is working with TU 17.1

**Comment by OoogaBoonga** [comment]
Alright thank you, didnt realise my fifa had updated
