### ISSUE TITLE
My game wont start and it opens ea app instead of fifa 23

### ISSUE THREAD

**Issue by ggedibu** [xAranaktu/FIFA-23-Live-Editor#339]
please help guys

**Comment by xfr4g6er** [comment]
You need to wait for the update it gonna be released today

**Comment by ggedibu** [comment]
hes said that it released 1.35 pm cest but its already almost 2pm cest, what to do??

**Comment by ias-vegas13** [comment]
I don't think he will release v23.1.3.5 because v23.1.3.6 already exists. Probably on thursday (I think) which completes one week of patreon release.

**Comment by ggedibu** [comment]
he said that it will be released on the 21 of august tho,, no the V23.1.35 but the v23.1.3.6

**Comment by ryonardi** [comment]
He released it on his Patreon for 23.1.3.5. I just used it but still didn't work for me. I think we have to wait for the 23.1.3.6 public release. And I don't have a clue which date is.

**Comment by louieaamer** [comment]
It releases on the 24th of August.

**Comment by ryonardi** [comment]
Ah, I see. So it will be 1 week after Patreon post. Thanks for the info

**Comment by jfxrbes** [comment]
whats the chances he releases it today since it really shouldve already been out?

**Comment by xAranaktu** [comment]
> whats the chances he releases it today since it really shouldve already been out?

You can download [v23.1.3.5](https://www.patreon.com/posts/87670936) from patreon already, but it won't work anyway with TU 17.1 and because of that I also will not upload it on github for now cus it will only again generate more unecessary comments.
