### ISSUE TITLE
v 23 1.3.5 i indirdim ancak yine aynı hatayı alıyorum

### ISSUE THREAD

**Issue by ramazan1434** [xAranaktu/FIFA-23-Live-Editor#340]
![Adsız](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/142820344/3ed92d2e-2df7-49ec-afa2-1b7aa521a5c1)

**Comment by serhatsenkall** [comment]
yayınlama saatide geçti bu pavel ne iş anlamadım

**Comment by serhatsenkall** [comment]
ramazan sana ulaşaabileceğim bi yer var mı dosyayla ilgili

**Comment by bytalhaa** [comment]
@serhatsenkall  @ramazan1434 aynı hatayı bende alıyorum çözdünüz mü

**Comment by ramazan1434** [comment]
çözemedim

**Comment by ramazan1434** [comment]
> ramazan sana ulaşaabileceğim bi yer var mı dosyayla ilgili

ramazan7446    dc

**Comment by bytalhaa** [comment]
@ramazan1434 1.1.5 mi 1.3.5 mi

**Comment by ramazan1434** [comment]
v23 1.3.5 i indirdim

**Comment by serhatsenkall** [comment]
> @serhatsenkall @ramazan1434 aynı hatayı bende alıyorum çözdünüz mü



> @bytalhaa @ramazan1434 ekleyin dc beni yardımcı olmaya çalışıyım sarad11 dc

**Comment by Unique-19** [comment]
Hocam bir sorum var bir de cevap niteliğinde bir bilgim. Önce cevabı vereyim; 1.3.5 sürümü çıkacağı zamana kadar FIFA bir güncelleme değil 2 güncelleme birden aldı. TU 17 ve TU 17.1 . Dolayısıyla 1.3.5, TU17 ile uyumlu iken 1.3.6 güncellemesi de TU 17.1 ile uyumlu. Zaten (yanlış hatırlamıyorsam ismini) changelog dosyasına bakınca orda yazıyor. Şimdi soruma geleyim, 1.3.5 i nereden indirdin acaba ?

**Comment by Walk4way** [comment]
1.3.5 tu17 için ama oyun 17.1 sürümünde. 1.3.6 lazım son sürüm için

**Comment by Walk4way** [comment]
https://www.patreon.com/posts/fifa-23-live-v23-87670936

**Comment by Unique-19** [comment]
> https://www.patreon.com/posts/fifa-23-live-v23-87670936

Teşekkür ederim.

**Comment by serhatsenkall** [comment]
> Hocam bir sorum var bir de cevap niteliğinde bir bilgim. Önce cevabı vereyim; 1.3.5 sürümü çıkacağı zamana kadar FIFA bir güncelleme değil 2 güncelleme birden aldı. TU 17 ve TU 17.1 . Dolayısıyla 1.3.5, TU17 ile uyumlu iken 1.3.6 güncellemesi de TU 17.1 ile uyumlu. Zaten (yanlış hatırlamıyorsam ismini) changelog dosyasına bakınca orda yazıyor. Şimdi soruma geleyim, 1.3.5 i nereden indirdin acaba ?

doğru söyledin hocam bu update çalışmıyor bir kaç gün sonra bir update gelicek onla çalışıcak bu gidişle bizi fifa 22 döndürücekler

**Comment by xAranaktu** [comment]
Only [Live Editor v23.1.3.6](https://www.patreon.com/posts/87829285) is working with TU 17.1

**Comment by serhatsenkall** [comment]
> Only [Live Editor v23.1.3.6](https://www.patreon.com/posts/87829285) is working with TU 17.1

when will come ?

**Comment by Unique-19** [comment]
> > Only [Live Editor v23.1.3.6](https://www.patreon.com/posts/87829285) is working with TU 17.1
> 
> when will come ?

24 Aug as I know.
