### ISSUE TITLE
No game found after 1200 attempts.

### ISSUE THREAD

**Issue by qwertyboiz** [xAranaktu/FIFA-23-Live-Editor#347]
I am using the latest version of Live Editor (v23.1.3.6) however when I run the game it does not open, goes to the EA app and presents me with the 1200 attempts error. Any solutions? Thanks.

**Comment by xAranaktu** [comment]
send log files

**Comment by qwertyboiz** [comment]
[log_launcher_24-08-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12430710/log_launcher_24-08-2023.txt)
Is this the one you mean?

**Comment by xAranaktu** [comment]
Live Editor is not able to inject dll into game process
```
PID: 11716 ERROR: [Injector::DoInjectDLL] OpenProcess failed: Access is denied. (5)
```

Perhaps because it is blocked by your antivirus. Add LE to exceptions in your AV.

**Comment by qwertyboiz** [comment]
It's not blocked. Anything else it could be?

**Comment by xAranaktu** [comment]
I don't know what else can cause this error

**Comment by qwertyboiz** [comment]
It seems to give me a different error each time.
[log_launcher_24-08-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12439280/log_launcher_24-08-2023.txt)

**Comment by xAranaktu** [comment]
I don't see any other errors. Your game either doesn't start at all or the live editor is blocked by something causing `Access is denied` error

**Comment by qwertyboiz** [comment]
For reference, logging on on an administrator account solves the issue.
