### ISSUE TITLE
Live editor does not save my player changes in my career

### ISSUE THREAD

**Issue by qPayn** [xAranaktu/FIFA-23-Live-Editor#349]
Im customising my own player in live editor, adding tattos, changeing hair, etc. I save it but after I play one match the player returns to his original looks, like all the changes ive made dissapear and he returns to default. Does anyone know how to save my changes without having to add them after every match?

**Comment by xAranaktu** [comment]
You can't. The game design doesn't allow to permanently change values that are stored in `players` table in the database. Nothing can be done with that.
