### ISSUE TITLE
Games start and Closes. 

### ISSUE THREAD

**Issue by Nirvana16** [xAranaktu/FIFA-23-Live-Editor#35]
My EA app updated yesterday and now the game opens and closes immediately. =( 

Following the release tables I don't see new releases on the schedule, please tell me that project has not been abandoned

**Comment by Danielgamer8358** [comment]
I know right it happened to me too :(

**Comment by Vavik16** [comment]
+

**Comment by xAranaktu** [comment]
Live Editor doesn't work with FIFA 23 Title Update 6. It may take a few days or weeks to update it. The update may also never come, idk. I don't know how long exactly it will take me to figure out what EA decided to do this time to prevent "cheaters".

**Comment by Nirvana16** [comment]
Thanks man! Everyone who I see downloading the LE are just using it to customize their gaming experience. Mainly in Career Mode. Honestly, EA should see LE and its project as something that boosts Fifa sales and not the other way around.

I hope you get bypass the EA as soon as possible. Unfortunately, my condition in Brazil does not allow me to contribute to your Patreon at this time, but I have already shared it with the communities I participate in. Your project is incredible, I wish u much success. u deserver it

**Comment by Xrst1908** [comment]
xAranaktu Ι would suggested to you find a way removing completely EA Anticheat. There is a huge problem for us... Thanks a lot.

**Comment by JakobSBG** [comment]
Bro the LE is an amazing tool to have in my career modes, EA are so annoying making it harder to mod the game cause of "cheaters", xAranaktu huge legend.

**Comment by daviewigati** [comment]
sowhat i have to do? because if i open launcher and run the game, its open then its close again. what i have to do?

**Comment by daviewigati** [comment]
please help

**Comment by Nirvana16** [comment]
> sowhat i have to do? because if i open launcher and run the game, its open then its close again. what i have to do?

u have to wait. Or, if u really wanna help this project u can sponsor his patreon:  https://www.patreon.com/xAranaktu

**Comment by daviewigati** [comment]
Okay, for how long?

**Comment by xAranaktu** [comment]
> sowhat i have to do? because if i open launcher and run the game, its open then its close again. what i have to do?

Only Live Editor [v23.1.1.6](https://www.patreon.com/posts/77189322) is working with Title Update 6.
Public release on 20th January (as mentioned in [Release Schedule](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=0))
