### ISSUE TITLE
v23 .1.3.6 yı indirdim ancak oyun açılınca bu hatayı alıyorum yardım edermisiniz

### ISSUE THREAD

**Issue by ramazan1434** [xAranaktu/FIFA-23-Live-Editor#350]
![Adsız](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/142820344/4cdce54a-6954-4cb1-8f20-8217c3e31c65)

**Comment by xAranaktu** [comment]
English?

**Comment by ramazan1434** [comment]
modlu oynamak istiyorum ama
