### ISSUE TITLE
DirectX Error when trying to open the game only by launcher

### ISSUE THREAD

**Issue by iulian47s** [xAranaktu/FIFA-23-Live-Editor#356]
Hello, I have a problem when I try to open the game via Live Editor, I am getting an DirectX Error
DirectX function
m_renderer->createSwapChain(&swapChainDesc,&fullscreenDesc, m_hWnd ........
Failed with E_INVALIDARG ("An invalid parameter was passed to the returning function.")

When I open the game normally I can play it, but I get this error only opening via LE
Any solutions please?

**Comment by xAranaktu** [comment]
Disable loading images in LE settings if this appear when you open player editor. Otherwise it's caused by the mods you have installed or 3rd party overlays that you have and that doesn't work with live editor.

**Comment by iulian47s** [comment]
I don't have any mods or anything to interfere with it, both folders are clean, no mods or 3rd party apps installed.

**Comment by xAranaktu** [comment]
Send log files

**Comment by iulian47s** [comment]
[Logs.zip](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12440931/Logs.zip)

**Comment by iulian47s** [comment]
Are the files good?

**Comment by xAranaktu** [comment]
LE is not able to initialize its UI, but I don't know why. I don't see any error in logs. Can't help you, sorry.
