### ISSUE TITLE
DirectX Error after importing miniface from PC

### ISSUE THREAD

**Issue by Sarkyas** [xAranaktu/FIFA-23-Live-Editor#357]
Hello, I added a miniface from my computer and my Live Editor is totally broken, when i will try to open for example team formation, the image of formation with players will not load and boom DirectX Error and when i will try to open player editor with imported miniface it will crash too. Thanks for advices.

**Comment by xAranaktu** [comment]
Delete the file from `C:\FIFA 23 Live Editor\mods\root\Legacy\data\ui\imgAssets\heads`, or disable loading images in LE settings then open the player in player editor and delete his miniface.
