### ISSUE TITLE
L.E. not launching

### ISSUE THREAD

**Issue by Jhoantrooper** [xAranaktu/FIFA-23-Live-Editor#359]
Log: [log_launcher_26-08-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/12446086/log_launcher_26-08-2023.txt)

**Comment by xAranaktu** [comment]
I only see that Live Editor is not able to create legacy folders because you have changed the live editor mods directory and something bugged out. Delete `FIFA 23 Live Editor` folder from `C:`

**Comment by Jhoantrooper** [comment]
I just did that and it actually worked, tksm, im new to this mods thing so thanks for helping

**Comment by Jhoantrooper** [comment]
I just did that and it actually worked, tksm, im new to this mods thing so thanks for helping
