### ISSUE TITLE
Every time i try to start up the game with live editor it just crashes after a few secs

### ISSUE THREAD

**Issue by Kaca156** [xAranaktu/FIFA-23-Live-Editor#36]
I dont know what to do with it anymore. Ive tried it with LE 1.1.1 and 1.1.6 and it just doesent work. Ive tried turning up the delay but nothing. Please help me cuz i wanna play my fifa CM and without mods its terrible.

**Comment by PaiPedro** [comment]
Same thing happens to me bozo.Have u solved it ?

**Comment by mustafesimba1** [comment]
Its because there was a new FIFA update 2 days ago. You have to wait for Aranaktu to make a new version of Live Editor

**Comment by Kaca156** [comment]
bro i kinda thought it was bcs of that update i just wanted to make sure if any other people have this problem or its just me so thx guys
