### ISSUE TITLE
failed to open game after 1200 attempts in 1.1.6

### ISSUE THREAD

**Issue by Oduded** [xAranaktu/FIFA-23-Live-Editor#37]
help, am i the only one who experience this ? "(

**Comment by Dany0712** [comment]
No, the new update broke the live editor. I saw that Aranaktu released a new version that work with it so just get that one.

**Comment by Oduded** [comment]
> No, the new update broke the live editor. I saw that Aranaktu released a new version that work with it so just get that one.

yes but im using the latest version of it..

**Comment by siyah0** [comment]
> > Hayır, yeni güncelleme canlı düzenleyiciyi bozdu. Aranaktu'nun onunla çalışan yeni bir sürüm yayınladığını gördüm, o yüzden onu alın.
> 
> evet ama en son sürümünü kullanıyorum..
i have the same problem
i have the same problem

i have the same problem



> > No, the new update broke the live editor. I saw that Aranaktu released a new version that work with it so just get that one.
> 
> yes but im using the latest version of it..

i have the same problem

**Comment by Renzyx** [comment]
> > No, the new update broke the live editor. I saw that Aranaktu released a new version that work with it so just get that one.
> 
> yes but im using the latest version of it..

the newest version are currently not made for public yet mate it's only for patreon members atm.

**Comment by hendrixxx11** [comment]
same here :(

**Comment by hendrixxx11** [comment]
The new update is only available on patreon atm

**Comment by Cicvara99** [comment]
> The new update is only available on patreon atm

did you have it?
if you have can you send files?

**Comment by jaker37** [comment]
Hey did anyone manage a fix for this i still can't get it to work with latest version?

**Comment by lautid11** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/127547415/224407073-7137b1cc-4f67-483b-85a4-8dee256751d1.png)
si lo ponen asi lo solucionan

**Comment by whatupomer** [comment]
has anyone found a solution for this please help

**Comment by whatupomer** [comment]
has anyone found a solution for this please help
