### ISSUE TITLE
FIFA 23 CLOSES UPON OPENING

### ISSUE THREAD

**Issue by Gabhoflai** [xAranaktu/FIFA-23-Live-Editor#38]
When executing the Live Editor launcher application and running it with the origins disconnected, the Fifa application opens and closes instantly. Any solution to the problem or is it because of the new patch 6?

Thank you for your attention

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-23-Live-Editor/issues/35#issuecomment-1382709267
