### ISSUE TITLE
I open game with Live editor and it Crashes seconds after opening game

### ISSUE THREAD

**Issue by Xen0s1** [xAranaktu/FIFA-23-Live-Editor#39]
I have the live editor open and run it manually through the EA app. The game opens and it bypasses the anti cheat. Though Seconds after the Game opening, it crashes and go's back to the EA app. Will this be fixed in the 23.1.1.6, as I saw in the changelog text?

**Comment by Xen0s1** [comment]
> Game was updated, you need Patreon release (23.1.1.6) to play with Live Editor.

How do I get patreon?

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-23-Live-Editor/issues/35#issuecomment-1382709267
