### ISSUE TITLE
Is there a way to launch FIFA23 offline?

### ISSUE THREAD

**Issue by GotGimhong** [xAranaktu/FIFA-23-Live-Editor#40]
Regardless of the live editor and the cheat table, I've tried running Steam and EA app in offline mode, but unfortunately failed to launch FIFA23. I succeeded in launching FIFA23 only when EA app ran in online mode and was connected to EA server. Therefore, I had to use the live editor and the cheat table online. Perhaps I'm so lucky that my account is still not banned.

Is there a way to launch FIFA23 offline? Or we have to use the live editor and the cheat table online?

**Comment by xAranaktu** [comment]
Switch to offline mode in EA App. I don't know why it doesn't work for you, never heard anyone had problem with that.
Alternative solutions are pretty obvious, you have to block every single connection to EA servers in your firewall or turn off your internet when you play.

**Comment by GotGimhong** [comment]
All right, it's really strange, but anyway thank you for your suggestions.

Once I guessed that there's a listener in FIFA23.exe, to boot the game after connected to EA servers. Because when EA App runs offline, the game fails to launch without any warning and error, and FIFA23.exe isn't found in task manager.

**Comment by neymarmessisuarez** [comment]
I also can't run fifa 23 with steam and ea app offline. I have already tried to open in offline mode and with my internet turned off. Can you help me with this problem?

**Comment by GotGimhong** [comment]
> I also can't run fifa 23 with steam and ea app offline. I have already tried to open in offline mode and with my internet turned off. Can you help me with this problem?

We meets the same problem bro.

In order to run FIFA23 with the live editor,  I keep Steam and EA App running online, and after FIFA23 is launched, I block the connection to FIFA23 servers. However I'm no sure that it really works, or maybe it's a fluke that my account never gets banned.
