### ISSUE TITLE
keeps crashing after it says "press shift+f1 to access online features"

### ISSUE THREAD

**Issue by ACETHEBOLD** [xAranaktu/FIFA-23-Live-Editor#42]
whenever i launch fifa 23 it crashes after it says "press shift+f1 to access online features".  even after i went in offline mode and disconnected my internet it still keps doing this.  anyone know why?

**Comment by chrisomaticus** [comment]
I have the same problem seems that it has something to do with the last update.

**Comment by JOHN127704** [comment]
me too
