### ISSUE TITLE
Walkout Anthems and Chants are Bugged

### ISSUE THREAD

**Issue by SparkleSparatic** [xAranaktu/FIFA-23-Live-Editor#46]
If you go on Create a Club or play as a team with an Anthem in General, the Audio sounds distorted and buggy and you can barely hear anything. Any fixes here?

https://user-images.githubusercontent.com/123327430/213936254-0fed0aae-af12-4bab-9777-cfee95ba9321.mp4

**Comment by xAranaktu** [comment]
The only "fix" is to disable chants in live editor settings.

**Comment by SparkleSparatic** [comment]
> The only "fix" is to disable chants in live editor settings.

How do I do that?

**Comment by xAranaktu** [comment]
![](https://i.imgur.com/Ius6deL.png)

**Comment by SparkleSparatic** [comment]
> ![](https://camo.githubusercontent.com/c5c19305889a52c4c72223a62233aee24d66990a7392050f7298ac45b6b8c3f3/68747470733a2f2f692e696d6775722e636f6d2f4975733664654c2e706e67)

So this sadly means I won't be able to play the game with the fun of the chants and anthems? Sad.

**Comment by xAranaktu** [comment]
> The chants were actually fixed in v23.1.2.4, I could not test with v23.1.2.5 cause the game crashed with it and with v23.1.2.6 the bug is back.

The strangest thing is that it's that the Live Editor update isn't a problem here. You can downgrade to TU11 and run it with v23.1.2.6 and the chants will work fine.

**Comment by xAranaktu** [comment]
Without any change in live editor. :) You see how it works...
