### ISSUE TITLE
Game crash after new update

### ISSUE THREAD

**Issue by JOHN127704** [xAranaktu/FIFA-23-Live-Editor#48]

**Comment by Hanson** [comment]
same +1

**Comment by SparkleSparatic** [comment]
Live Editor needs to be updated

**Comment by dozbek67** [comment]
I've downloaded Live Editor v23.1.1.6  again but it doesn't work again after update of the game

**Comment by kevin88duong** [comment]
I dont think the latest ver works with the new update, doesn't work for me either

**Comment by yanzhrd** [comment]
I use the origin app, I have turned off the internet, it still crashes

**Comment by Nirvana16** [comment]
I Think v23.1.1.6 no longer works after the last Update (23/01/20203). At least not for me.

**Comment by noRynx** [comment]
Mine isn't crashing but it's just stuck when trying to play world cup its stuck on "Checking for updates". I play offline in origin cuz its a share account btw

**Comment by twj515895394** [comment]
> I've downloaded Live Editor v23.1.1.6 again but it doesn't work again after update of the game

same too
