### ISSUE TITLE
Problems about integral verfication and game's update

### ISSUE THREAD

**Issue by GotGimhong** [xAranaktu/FIFA-23-Live-Editor#50]
Hi xAranaktu, so far I've found two problems about the live editor and I want to share them with you, which you may have already known.

The first problem is that the live editor seems to modify some game files to bypass the anti cheat, which makes the game unable to launch again as it fails to pass integral verfication.

The second problem is that everytime you release a latest live editor, it just works until the next FIFA23's update. We're likely to meet a crash problem if we go on using the live editor after the update. It seems that the official has noticed the live editor. Perhaps it's bothered not only for users but also for you to keep updating the live editor. Do you have a better way to solve this problem?

**Comment by GotGimhong** [comment]
Brilliant, the live editor v23.1.1.6 still works after today's update.

**Comment by xAranaktu** [comment]
```
The first problem is that the live editor seems to modify some game files to bypass the anti cheat, which makes the game unable to launch again as it fails to pass integral verfication.
```

The only file that's modified by Live Editor is `EAAntiCheat.GameServiceLauncher.exe` and the live editor will restore original one as soon as possible. I don't have any problems with switching between clean version and version with live editor. If restoring original file fails for you for some reason then you will either have to restore that file manually or repair the game whenever you want to play without live editor.

```
The second problem is that everytime you release a latest live editor, it just works until the next FIFA23's update.
```
Well, I expected that, that's normal when company want to combat cheaters. Anyone from EA can download live editor, check how it works, check how the anti-cheat is bypassed and "break" my bypass with new game update. The only solution I see for this is to keep live editor private, for only small group of ppl, but that also doesn't guarantee it will work after the game update and also doesn't make sense for me. You can also just turn off the auto updates... and not update the game until new version of live editor arrive with support for the next title update.

**Comment by GotGimhong** [comment]
Got it, it really helps. Thank you for your detailed reply.
