### ISSUE TITLE
Crowd bug/error

### ISSUE THREAD

**Issue by DrExcalibur1** [xAranaktu/FIFA-23-Live-Editor#51]
When I open Live Editor and play a game the crowd has some kinda echo sounds when they sing something. I opened Fifa without live Editor to see if it's a game problem but the crowd was singing normally but when I play it in Live Editor it's like aliens are singing / chanting.

**Comment by arafuru** [comment]
Same

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-23-Live-Editor/issues/46
