### ISSUE TITLE
Fifa main menu won't load after loading live editor 

### ISSUE THREAD

**Issue by Zim-Zimmer** [xAranaktu/FIFA-23-Live-Editor#52]

**Comment by fepetri** [comment]
same problem here

**Comment by jacky13277** [comment]
hi, I'm no expert or anything but I had the same issue and it was really annoying me. I just deleted all Live Editor files then redownloaded the latest version and somehow (no idea how) it fixed the issue. hopefully this works for you guys too. if not, sorry!

**Comment by Zim-Zimmer** [comment]
> hi, I'm no expert or anything but I had the same issue and it was really annoying me. I just deleted all Live Editor files then redownloaded the latest version and somehow (no idea how) it fixed the issue. hopefully this works for you guys too. if not, sorry!

I tried that many times and unfortunately it did not work even on the newer live editor

**Comment by jacky13277** [comment]
ah sorry bro idk then :(

**Comment by Thrasher935** [comment]
You need to hide Live Editor, press F9, if doesnt work View tab "hide live Editor".

**Comment by fifa23wsi** [comment]
bro just press F9

**Comment by insideforward** [comment]
Lol aye, u have to press f9 on opening or the game will be stuck before
whatever player wanders into the screen. This is only since the live editor
now loads at the same time as the game, rather than a few seconds after.

**Comment by Zim-Zimmer** [comment]
> You need to hide Live Editor, press F9, if doesnt work View tab "hide live Editor".
