### ISSUE TITLE
Again.. the game crashes every time i try to load it up with LE.

### ISSUE THREAD

**Issue by Kaca156** [xAranaktu/FIFA-23-Live-Editor#54]
This has already happend not too long ago. Its probably bcs of a new patch/update or sum, but i just wanted to make sure. Does this happen to ya too guys?

**Comment by Lookgoodok** [comment]
it's because of the newest update, wait a couple more days and Aranaktu will most likely release a newer version.

**Comment by s9be** [comment]
same issue happened after the new update F EA

**Comment by xAranaktu** [comment]
Both LE v23.1.1.6 and LE v23.1.1.7 is working fine with TU6, TU6.1 and TU7. Open log file and if you see this error:
```
[00:21:04.265] [9156] [ERROR] [HookMgr::AddHook] PLH failed 13
```
Then all you need to do is to delete the live editor and download it again..

**Comment by yanzhrd** [comment]
same issue, bro, after turning off the online mode the game crashes
