### ISSUE TITLE
skill points

### ISSUE THREAD

**Issue by tris095453453** [xAranaktu/FIFA-23-Live-Editor#56]
is there a whey yo get 999 skill points in my carrer? like in this video https://www.youtube.com/watch?v=JmGPTSVe8e4&t=101s

**Comment by xAranaktu** [comment]
You can do this only with cheat table.
https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/999-Skill-Points

**Comment by tris095453453** [comment]
can u also edit the xp with live editor

**Comment by xAranaktu** [comment]
no
