### ISSUE TITLE
Crash when trying to edit certain Team Leverkusen

### ISSUE THREAD

**Issue by Jidem0110** [xAranaktu/FIFA-23-Live-Editor#63]
For some reason a DirectX crash happens when i try to edit them in LE
![image](https://user-images.githubusercontent.com/124844176/217678353-51bb9f9c-480f-4421-831d-df6e21f76ff3.png)

**Comment by Jidem0110** [comment]
I updated my driver and its still the same

**Comment by xAranaktu** [comment]
I guess you have modified their crest and that's what is causing the crash. Delete it. If not then I don't know, but probably disabling loading images in live editor settings will fix that.

**Comment by Jidem0110** [comment]
Ok so basically i turned off my mod which adds new league logos and players and it lets me edit on live editor but when i turn it on it dosent work which is weird because every single other team that i have edited works and ive barely edited leverkusen, I also have another problem that other mods also have ever since title update 6.1 came out my career mode crashes at a specific date which ive been trying to figure out ever since
