### ISSUE TITLE
Players Editors don't working with mods

### ISSUE THREAD

**Issue by JuninZ1CO** [xAranaktu/FIFA-23-Live-Editor#65]
Basically just click on the **"players"** tab and the game **crashes**.
I already reinstalled the **Live Editor** and deleted the **offset_cache** as a guy said in another post and don't work :/
[log_11-02-2023.txt](https://github.com/xAranaktu/FIFA-23-Live-Editor/files/10712595/log_11-02-2023.txt)
![image](https://user-images.githubusercontent.com/125109734/218239734-7da5fc21-ad62-413a-ad00-a0cf4ce5e0b7.png)

**Comment by xAranaktu** [comment]
Players Editors don't working with **SOME** mods. If the one you are using doesn't work with live editor then well... unlucky. Won't be fixed.
