### ISSUE TITLE
Live Injector failed 1200 attempts

### ISSUE THREAD

**Issue by jaker37** [xAranaktu/FIFA-23-Live-Editor#68]
Had to update to EAplay and now the launcher wont work latest version. Have these two lines of code but dont know what access is denied its not run as administrator thats turned off.
PID: 3732 ERROR: [Injector::DoInjectDLL] OpenProcess failed: Access is denied. (5)
PID: 6392 ERROR: [Injector::DoInjectDLL] OpenProcess failed: Access is denied. (5)

**Comment by jaker37** [comment]
@xAranaktu

**Comment by RenisRed** [comment]
this happens since EA App. idk why, i'm truly devastated

**Comment by whatupomer** [comment]
has anyone found a solution for this please help
