### ISSUE TITLE
INVALID CHARACTER

### ISSUE THREAD

**Issue by leandrohenrii** [xAranaktu/FIFA-23-Live-Editor#7]
![image](https://user-images.githubusercontent.com/117613571/200211859-f6efd46b-494b-42d7-ae34-62580c5b11e1.png)

**Comment by leandrohenrii** [comment]
Version v23.1.0.1 open but not work, and the version v23.1.0.3 do not open and display that critical Error

**Comment by xAranaktu** [comment]
Not a bug. As the error says, put live editor in directory that contains English only characters.
