### ISSUE TITLE
EA App

### ISSUE THREAD

**Issue by SpaceRma** [xAranaktu/FIFA-23-Live-Editor#70]
![image](https://user-images.githubusercontent.com/125313434/218573611-f0e9056c-a61a-4e03-9bda-03e328de382e.png)

Can Live Editor work with the EA app ?

**Comment by xAranaktu** [comment]
Yes. I'm using EA App and don't have any problems.

**Comment by SpaceRma** [comment]
Okay, thank you for all your work
