### ISSUE TITLE
How to trigger Transfers ?

### ISSUE THREAD

**Issue by zaytsruss** [xAranaktu/FIFA-23-Live-Editor#71]
Can you trigger transfers to a specific team in my player career with live editor ? i just remember it from previous year.

**Comment by Petronel12** [comment]
yes you can, use the cheat table for that

**Comment by xAranaktu** [comment]
You can create transfer offer with the [cheat table](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/Player-Career-Transfer-Offer). It's currently not possible with the live editor.
