### ISSUE TITLE
Game Menu won't load

### ISSUE THREAD

**Issue by jdawg567** [xAranaktu/FIFA-23-Live-Editor#74]
Whenever I try to run Live Editor, the main menu doesn't load completely. I can see the black square where news would be and sometimes a random player but the options (play modes,setting,etc.) don't populate. Would this be due to the new Fifa update that just dropped?

**Comment by xAranaktu** [comment]
To be able to interact with the game press F9 to hide live editor, or go to View -> Hide Live Editor
