### ISSUE TITLE
Players issue

### ISSUE THREAD

**Issue by enricozsp** [xAranaktu/FIFA-23-Live-Editor#75]
When I select the "players" option to generate a miniface, the game closes

**Comment by xAranaktu** [comment]
Change live editor mods directory in settings to somewhere that doesn't require admin rights.

**Comment by enricozsp** [comment]
Like where

**Comment by enricozsp** [comment]
Cuz didn't work

**Comment by enricozsp** [comment]
Also, I'm using with mod manager

**Comment by enricozsp** [comment]
Can't find the documents folder on LE 😭

**Comment by enricozsp** [comment]
> 

I've found the documents folder, still crashing the game

**Comment by enricozsp** [comment]
Anyone have any other idea?
