### ISSUE TITLE
FIFA 23 LE Not working with EA App

### ISSUE THREAD

**Issue by Furqan04** [xAranaktu/FIFA-23-Live-Editor#76]
I have tried uninstalling and reinstalling the EA APP as well as FIFA 23 itself but since the switch from Origin I have not been able to load the game in offline via the LE. All that it shows is the error code EC: 203 and doesn't work. Any help in resolving this would be appreciated. I am using the latest version 1.1.9. Thank you.

**Comment by jfxrbes** [comment]
this LE isnt the upadted one, gotta work for him to finish and upload the file for this title update

**Comment by Moko3636** [comment]
I am having the same problem. Live Editor with EA app does not work and gives an error. Thanks everyone in advance

**Comment by wczmich** [comment]
Your EA App is probably not running with elevated priviledges (as administrator). Unfortunatelly it is not enough to right click on app icon and start it as administrator - you have to set "run as administrator" property on executable files properties - that worked for me

**Comment by Furqan04** [comment]
How can I do that?

**Comment by Furqan04** [comment]
I tried the method. It didn't work

**Comment by wczmich** [comment]
check if all ea app processes are elevated : https://binaryfork.com/windows-process-admin-rights-check-2381

alternatively you can still use origin after making a change to its config xml file 

1. Open C:\ProgramData\Origin\local.xml in notepad
2. Add new key there:
<Setting key="MigrationDisabled" type="1" value="true" />

Dont know how long will it work but seems to work for now
