### ISSUE TITLE
Fifa23 Live Editor not working Ea app

### ISSUE THREAD

**Issue by Moko3636** [xAranaktu/FIFA-23-Live-Editor#78]
Live Editor not working since Origin migrated to Ea app. Even though I'm using the 1.9 Live Editor version, it won't open. I am getting ec 203 error. Thanks in advance

**Comment by wczmich** [comment]
Your EA App is probably not running with elevated priviledges (as administrator). Unfortunatelly it is not enough to right click on app icon and run as administrator - you have to set "run as administrator" property on executable files properties - that worked for me

**Comment by Cartooonyttt** [comment]
Even after doing what you said it doesnt work is says that you need to have origin launcher

**Comment by wczmich** [comment]
check if all ea app processes are elevated : https://binaryfork.com/windows-process-admin-rights-check-2381

**Comment by DrCoomerPhD** [comment]
> check if all ea app processes are elevated : https://binaryfork.com/windows-process-admin-rights-check-2381

what if they're not elevated? like EADesktop.exe, it isn't elevated
