### ISSUE TITLE
Hotkey not working

### ISSUE THREAD

**Issue by kamski4998** [xAranaktu/FIFA-23-Live-Editor#81]
Hello im having this issue where when I start the game everything works except the menu, it wont open with the hotkeys, it just opens at the beginning

**Comment by xAranaktu** [comment]
Press F9. If that doesn't work then maybe you have changed the hotkey and the easiest fix would be probably re-downloading the live editor. Otherwise, I don't know what may cause this. Maybe DS4Windows or other software that you are running in background and somehow remaps the keys.
