### ISSUE TITLE
Live editor failed to launch

### ISSUE THREAD

**Issue by IshanChakrabortyYT** [xAranaktu/FIFA-23-Live-Editor#85]
- [ ] No game found after 1200 attempts.

@xAranaktu Please check this.

![image](https://user-images.githubusercontent.com/102155394/227711617-e1b2fc3f-9761-4c98-b2b8-7096e7d24147.png)

**Comment by IshanChakrabortyYT** [comment]
@xAranaktu Also I am getting this error.

> No game found after 1200 attempts.
> Access is denied (5).

![image](https://user-images.githubusercontent.com/102155394/227733032-89f72b0c-5d72-40ed-8822-59b268ed6ae8.png)

@xAranaktu Please help here I am not unable to launch the game.

**Comment by xAranaktu** [comment]
No solution for this.
