### ISSUE TITLE
game doesn't launch

### ISSUE THREAD

**Issue by maxGEwilk** [xAranaktu/FIFA-23-Live-Editor#89]
every time I go to launch the game through FIFA live editor the game just doesn't launch, bare in mind its worked for me before just does this from time to time, any info would be great :)

**Comment by maxGEwilk** [comment]
Also im i downloaded the newer update 1.2.1 and still the same problem :(

**Comment by maxdlpee** [comment]
Try 23.1.2.2, I was having the same issue and that version fixed it.
