### ISSUE TITLE
FIFA Update 10

### ISSUE THREAD

**Issue by Kobi-Blade** [xAranaktu/FIFA-23-Live-Editor#93]
Live Editor v23.1.2.2 doesn't work on latest FIFA version, was to expected after a long run with no issues.

**Comment by xAranaktu** [comment]
If you didn't had problems with v23.1.2.1 then you can still use it

**Comment by xAranaktu** [comment]
These logs are from 1.2.2. It won't work. 
You can also try [v23.1.2.3](https://github.com/xAranaktu/FIFA-23-Live-Editor/releases/download/v23.1.2.3/FIFA.23.LE.v23.1.2.3.zip)

**Comment by zangafa** [comment]
try this version but still not working also version --> FIFA.23.LE.v23.1.2.3
