### ISSUE TITLE
Game crashing when opening player menu

### ISSUE THREAD

**Issue by zPorto** [xAranaktu/FIFA-23-Live-Editor#94]
First of all, thank you for all your effort on creating this tool and making it even better @xAranaktu!
I'm having problems with this latest update. Whenever I click on any menu from the dropdown list, my game crashes. It worked fine on the last few versions...

Is there something I might be doing wrong?

Thank you!

**Comment by xAranaktu** [comment]
send log files

**Comment by zPorto** [comment]
> send log files

Log File
[https://pastebin.com/UVnXzDvV](url)

Launcher Log File
[https://pastebin.com/0AX9ikgG](url)

**Comment by xAranaktu** [comment]
You are using mods that doesn't work with live editor.
