### ISSUE TITLE
Standings

### ISSUE THREAD

**Issue by fotisbellos** [xAranaktu/FIFA-23-Live-Editor#98]
I'm playing cm and i try to forcefully relegate chelsea so that i can do a rebuild from the championship.. i reduce the points but when i proceed to the next season chelsea is still in the pl.. am i doing something wrong or the change in points doesn't affect the final standings ?

ps currently i'm not managing chelsea or a pl team so their league results are automated

**Comment by xAranaktu** [comment]
You can try to add them to [disliked teams](https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Editing-Fixtures#favourite-and-disliked-teams). If that won't work then nothing can be done with that.
